### ISSUE TITLE
wasm-bindgen does not have `enable-intern` features. Examples fail to run

### ISSUE THREAD

**Issue by MarcoPolo** [Pauan/rust-dominator#17]
This looks great, but I ran into an issue when I tried to run the examples. 

```
rust-dominator|master ⇒ cargo +nightly build
    Updating crates.io index
error: failed to select a version for `wasm-bindgen`.
    ... required by package `dominator v0.5.0 (/Users/marco/code/rust-dominator)`
versions that meet the requirements `^0.2.45` are: 0.2.48, 0.2.47, 0.2.46, 0.2.45

the package `dominator` depends on `wasm-bindgen`, with features: `enable-interning` but `wasm-bindgen` does not have these features.


failed to select a version for `wasm-bindgen` which could resolve this conflict
```

Probably because you just merged the enable-interning features in wasm-bindgen, and that hasn't been pushed to crates.io yet (?).

How are you running these?
Thanks!

**Comment by Pauan** [comment]
> This looks great

Thanks! Let me know if you have any questions.

> Probably because you just merged the enable-interning features in wasm-bindgen, and that hasn't been pushed to crates.io yet (?).

Yes, that's correct. A new version of wasm-bindgen should hopefully be released soon, and then I'll be able to publish a new version of dominator to crates.io

> How are you running these?

I have a local clone of wasm-bindgen (and wasm-bindgen-cli), and then I override the wasm-bindgen packages like this:

```toml
[patch.crates-io]
wasm-bindgen = { path = "../../../wasm-bindgen" }
wasm-bindgen-futures = { path = "../../../wasm-bindgen/crates/futures" }
wasm-bindgen-shared = { path = "../../../wasm-bindgen/crates/shared" }
wasm-bindgen-backend = { path = "../../../wasm-bindgen/crates/backend" }
wasm-bindgen-webidl = { path = "../../../wasm-bindgen/crates/webidl" }
js-sys = { path = "../../../wasm-bindgen/crates/js-sys" }
web-sys = { path = "../../../wasm-bindgen/crates/web-sys" }
```

However, I don't recommend doing all that. Instead, just do `git checkout 1cd3971a8101f38990fb0293310ed4fc119af3e1` to get the version of dominator right before the intern changes.
